name: Test

on:
  push:
    tags: [ 'v*' ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore SFTracker.Tests/SFTracker.Tests.csproj

    - name: Test
      run: dotnet test SFTracker.Tests/SFTracker.Tests.csproj --no-restore --logger "console;verbosity=normal"
